name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Format Code
      run: go fmt -x -mod=vendor ./...
    - name: Go Vet
      run: go vet -x -mod=vendor ./...
    - name: Build Binary
      run: go build -v --race ./...
  unit-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: go test -v -count=1 --race --cover --short ./...

